### ISSUE TITLE
Use requests instead of tornado (pluggable)

### ISSUE THREAD

**Issue by mbaechtold** [jaimegildesagredo/finch#9]
I just stumpled upon this great package during my research for a rest api consuming client and it looks very promising.

Is it possible to use requests instead of tornado for the client?

**Comment by larruda** [comment]
News?

**Comment by paulmelnikow** [comment]
Wren is in PyPI: https://pypi.python.org/pypi/wren

The updated source is here: https://github.com/bodylabs/wren
